language: python
python:
- '3.5'
- '3.6'
- 3.7-dev
install:
- pip install --upgrade pip
- make local-install
script:
- pytest
deploy:
  provider: pypi
  user: djcurtis
  password:
    secure: HrnBAP3HnDooqMNhOORgyrrdbMaT2S22fNvWGoTzAmtDiDhXtlpUz13ham5sXTC98Bs0p/LVTGPugWgQ2NoXw17F7L60ZpFFpPCHrSQ0gla+DGG0Qnu/nSQj3yFnijUWclSrc1xZEdSR+oXf0/6A2M/b4cTYM6u5VI44qJp3R5qDkJyEFyMUdCMFUnVTvHLVtnLimSocVwbNdF0YBg103+lzN7JrS0kQ29oJ+rmbDVK1LR1TBlilECASe0u5AscIkj5gJZFgJPgsq7BD4/7/UUEqKvr3KuXsa3gaOgIUMuPlD2du2Zgq3vBj+ryjoX/jwbdgLbj54Fq6aytQU1hgllvtFGC/1edqJw88Ww6ukQptT+h76pFAd09zv/u/EiGGRhaJTzaz3vSdAPLokd3tlKlKw9DQWhZ8CCmGq55n4Orzt8VjvjAaBwS3cqaqjXN3MHBTdm9dzjnk37xY3CtKoMukp3Qci82V3Ofdre48H2mofICN9dRPlDaNtQjzz4qAOlQ+2X/dZnq/szxpvC8052fUevVspUT9QsKIMw7ahPNv+fU3khnrROpe+aVLtyphSzUtm+nfaTfs6+vIQvatj1oE5NQSPv2u/PAa96H1uuajz+4IKL/whHMT4c8Mkw4STOdVbJZ8wz8xc3XvGWngQ3UbIMJj7fdih9En8MlReRQ=
  on:
    tags: true
  distributions: sdist bdist_wheel
