language: python
python:
- '3.6'
- 3.7-dev
install:
- pip install --upgrade pip
- make local-install
script:
- pytest
deploy:
  provider: pypi
  user: djcurtis
  password:
    secure: XpsWUgSdHCsyXyNXjPmLhTmrcbox/8Uofv29FZvV/L8BLVnjvm//fzhby306ASMaHJI3X5k2IYKQX5Wmt+gP/thQQx6a5kImIRXym4W9uvxOFCJY17EDAAYuggDEx6Jb1jzgODhJSk0ffR8V+eJ11fkOz/P+XRJHSb+S6cynoHG6vXVbAsGmqH4yNtb3oYh2RnxjEiD0eRyESP/jN1ts1kakVX87gIqhsitvsAASF3yW6xWlZbl7GANxxkLdkLf7tzm417+cxzV2IMD4H7XSd8C1NdvN/bHBpzurLDAkW4jAnWCZsMpw800n8mDiiDQ8vYQ1WjsNs5CMjv8rFndNncRPRZSd+GalL+0UC2bQkJcMj59VnIVEdZxhrv9sauPzotHcPIKuK2HnFiHncgtNb4Hyg+ABvJOparrMcDy+KEzLJKW4xCHlXuJJAkYDPNwQ7WcyzhKlGBAw/rXgvDtui/lvDbeK7x2Bva2UYpdPqgJJRYbnOVeihKLlUGKEHda9hYbVShLDwuBIOT8oWfOAt1w/sXZiLj9mBaaGyHDn/zRe0t7ubsA4roXO7il8xqOjwxP2i8/J++OZ52lQv0QKkdbz1U/sYH7MWOvZCs6skIa5REsv6yYU0AnROy8P6hnv7mEXwLQ8dZTqiLa8FKAPgk5mvIU5ttZhEKPSajh8pYE=
  on:
    tags: true
  distributions: sdist bdist_wheel
