language: python
python:
- '3.6'
- 3.7-dev
install:
- pip install --upgrade pip
- make local-install
script:
- pytest
deploy:
  provider: pypi
  user: "djcurtis"
  password:
    secure: "OJ22PzImZOEWBolMjyRdkVcZAlnBrfLgS1RMYKwRh+nQxY/7wbcwx3ViVo0daKkGrg0R3NGvHtgTeD29+N3mi0ukQTPsAHFIajbW7mcE/86NRusN3KFCqzf6ev2lbsg7N0RKzi+JHa0D4TvPF82yGEitqeAyhMMOskWVb+zzjhP/1PHp7AwsWBd+Xa8bLSM0shJG36JAlgvAS/2vHtovd/y14CRScVs5Yk682rfFnusrJq94UpkkBrBDal+dM0/G9pVC1BrBFC8Pci+NIfsYdr6rBZq43KZSMjuSs1nu2n6nKWNDjsSLYPNldbNQe69nLz4eBQyD3kQxF9bJvlR+vY+wx8+PHESMrXX5uMwTuU+ing+XTk6WLyRmD58yrq/kibjI6dy58rK6OzfZHfVXKWTy4qvvJ8H2k+qkz1myYjV79gIIXNCFt/d9F6Q/Qci0cv1C7dBLAmUlzFpSuPcBfE6yaVNCovCtGKDLzj6IYo3zQTlcDa2p5zTg6vGo64ASNFhIEOQdSShhijaF8dAGGSi7mMUDvGzZkj4d5FPJLNdQ292gB7nw7epSL6DZeZa5hY00NTOj7/QkfVzG5xCeByOcwsIwCIi2O+/X6Pff6jSby4f/ovazlNC9RjnSm9zp24PbiV40dN+wv6Ad1Xm7PJsNfXSNCNXBAt1Uq/0iGe8="
  on:
    tags: true
  distributions: sdist bdist_wheel
