language: python
python:
- '3.6'
- 3.7-dev
install:
- pip install --upgrade pip
- make local-install
script:
- pytest
deploy:
  provider: pypi
  user: djcurtis
  password:
    secure: PQt7AYhUkqHam+QMyUbu7IiYQ91ircG/RSYYfCIEFm5jgFbaDXjcoZIK9SZ+WxQqwFBKxwOGK2EcLBWVHESs9MIg6wBEz8hBAgyiII5lpTwD1MsonyAt1t6yl+3HHQX0yhkcddKePQeGYxgkA1rdRXlC/WuIL03wcvA4v5lw9MFt96l0y2DOZDD99pKyYtY4kRTcyiID6j1wsjYHiWySATrawdDNk/ZAVHXlsl/iyEfi6d7AMX0+7y+1QYvRX+enZV+SxivfVrAhC+a8hidcKAn2rt8AGansEc0Eqr7GysxowpDiNUR7Wpx7SIDEwcYbgVjtrF8S6yF1TauOaC8vi2okaANeKvbfnV16VUsT/8sz1281AnF8pCWrkdXSn0WYVocupWWdAFQqiyOJLU9qUALWuR4hbC7kq9bzNG/0jXyECYQL/d3Eh67eAjuZILR2OlKD8Iki679j+1r58wH962uiVpK1aN1pv6Ad1wnjsdL5TNonPoJkZwOI1zhNE4dWTJXyAgKiqjW+z6xIqK9UG1pcSTlKwyOAM/c9IO1qL4wZ9K7I832exBRy1hWRQENDKl3QN/IPPPmEQHQCLwr3U0w5sYCksYKA5zSbDOJc2MoIqkpyjQvkszMD5zYyM0MVNAp/PvKUcLBx7VPqe8X2dL8qPwy50okAROh0q2yxuig=
  on:
    tags: true
  distributions: sdist bdist_wheel
