language: python
python:
- '3.8'
install:
- pip install --upgrade pip
- make local-install
script:
- pytest
deploy:
  provider: pypi
  twine_version: 1.13.0
  username: GramediaDigitalNusantara
  skip_existing: true
  password: 
    secure: "mmk0mveEZpF7PRR5uIil9ax+ymf0kWfXHeYbVTf4oX1s0Pv0D6OT6WUFrgPABkIlrpBnX39Vy8fOyzxwtIkGlQVM37wnueFqRX6ZB4j5Gag7//M4h7Y2uSdLVWKBjr6qHf65DKibJn7wlR74qscvw5Ir4eMw5NXiBohqJl6Ja0whggabAwt5Goc2shXERcDRoXXUoGBqtW+TMdAZd8p4SQYnuLD8AVG1CEY8o/SJa3jruh7Ka2PNUsxjUjBC0m3XSNVmY9Ff2J8rWrsyiCoyT+GfShUAAdqmph0T3LI4A8BpY7a0cpRkVT1+T+Nj+2yuKMrgP/EYOmSpYorWlAdr7qzUA5KP0OcqNGIqp1GJ/NZIVhXqGCtWRxt8XqJ3ZKA63UxVOGWXloSBgD18oTph5Sb6TgsDv/hqSZwrMKPh/ME8+T2M59VmdmGaRepAfGm5ZNJEvgUuQVKZ3VcD9ON8Q9XnH/KOh3CBgMSEh9LlJJrqXWMODmJtO0NZMHjF1FAePa1aXiLqAhLcaktn/eKCjoLnT4VNa+TQM1sMxdgmGNn72ARHPbtzJ7koQaRSI2kYhQfgS+WNYZV08ySxqLf3Ir9pZ/tLyf2mfeKjI0sXQz/cET67hOAMk9UHmgX0Hbdfac+R4SC8Q035+6g2W4yuocoYCqAvVFeHz6xnFI48O14="
  on:
    tags: true
  distributions: sdist bdist_wheel
